# Generated by Django 5.1.6 on 2025-03-15 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('wa', '0003_userpreferences_audio_profiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStatistics',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('wa.exposurereport',),
        ),
    ]
