# Generated by Django 5.1.6 on 2025-03-14 05:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExposureReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_exposure_time', models.IntegerField()),
                ('trends', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('audio_settings', models.TextField(blank=True, null=True)),
                ('usage_history', models.TextField(blank=True, null=True)),
                ('ideal_volume', models.FloatField(default=50.0)),
                ('microphone_active', models.BooleanField(default=False)),
                ('last_adjusted_volume', models.FloatField(default=50.0)),
                ('low_freq_threshold', models.FloatField(default=50.0)),
                ('mid_freq_threshold', models.FloatField(default=50.0)),
                ('high_freq_threshold', models.FloatField(default=50.0)),
                ('sound_category', models.CharField(choices=[('music', 'Música'), ('podcast', 'Podcasts'), ('call', 'Llamadas')], default='music', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='HearingRiskNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warning_type', models.CharField(max_length=100)),
                ('date_and_time', models.DateTimeField(auto_now_add=True)),
                ('exposure_threshold', models.IntegerField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wa.exposurereport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wa.userpreferences')),
            ],
        ),
        migrations.AddField(
            model_name='exposurereport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wa.userpreferences'),
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=100)),
                ('headphone_compatibility', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wa.userpreferences')),
            ],
        ),
        migrations.CreateModel(
            name='AudioAdjustmentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommended_volume', models.IntegerField()),
                ('detected_noise', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wa.userpreferences')),
            ],
        ),
        migrations.CreateModel(
            name='SoundProfile',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('wa.userpreferences',),
        ),
    ]
