# Generated by Django 5.1.6 on 2025-03-14 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='name',
            field=models.CharField(max_length=151),
        ),
    ]
