# Generated by Django 5.1.6 on 2025-03-17 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wa', '0003_userpreferences_audio_profiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
