# Generated by Django 5.1.6 on 2025-03-17 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wa', '0004_alter_userpreferences_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
