# Generated by Django 5.1.6 on 2025-03-19 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wa', '0006_exposurereport_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exposurereport',
            name='total_exposure_time',
            field=models.IntegerField(default=0),
        ),
    ]
