# Generated by Django 5.1.6 on 2025-04-23 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wa', '0007_alter_exposurereport_total_exposure_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exposurereport',
            name='trends',
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='active_profile',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='exposurereport',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='exposurereport',
            name='total_exposure_time',
            field=models.IntegerField(),
        ),
    ]
