# Generated by Django 5.1.6 on 2025-05-14 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wa', '0008_remove_exposurereport_trends_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_code', models.CharField(max_length=6, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('group_bass', models.IntegerField(default=80)),
                ('group_mid', models.IntegerField(default=60)),
                ('group_treble', models.IntegerField(default=70)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_parties', to='wa.userpreferences')),
                ('participants', models.ManyToManyField(related_name='joined_parties', to='wa.userpreferences')),
            ],
        ),
    ]
