# Generated by Django 5.1.6 on 2025-05-14 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wa', '0009_partysession'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='current_party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wa.partysession'),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='in_party_mode',
            field=models.BooleanField(default=False),
        ),
    ]
