# Generated by Django 5.1.6 on 2025-05-14 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wa', '0010_userpreferences_current_party_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('party_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='wa.partysession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wa.userpreferences')),
            ],
        ),
    ]
